### ISSUE TITLE
Error 500 :Expected user agent to be a string

### ISSUE THREAD

**Issue by olabri** [bugsink/bugsink#13]
Hi thanks for a very promising project!

I have a bug that's bothering us when we try to resolve bugs,
access.log
> 10.8.68.135 - - [15/Nov/2024:07:27:49 +0000] "GET /issues/issue/8b5b9806-abac-4af7-9a9e-907b563e00dd/event/4c84e5d0-b477-4468-98ed-7e32e23f44f0/details/ HTTP/1.1" 500 886 "http://docker.internal:8000/issues/issue/8b5b9806-abac-4af7-9a9e-907b563e00dd/event/last/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"

error.log
> Internal Server Error: /issues/issue/8b5b9806-abac-4af7-9a9e-907b563e00dd/event/4c84e5d0-b477-4468-98ed-7e32e23f44f0/details/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bugsink/decorators.py", line 110, in wrapper
    return function(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bugsink/decorators.py", line 45, in wrapper
    return function(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/issues/views.py", line 423, in issue_event_details
    contexts = enrich_contexts_with_ua(parsed_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/events/ua_stuff.py", line 24, in enrich_contexts_with_ua
    user_agent = ua_parse(ua_string)
                 ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/user_agents/parsers.py", line 268, in parse
    return UserAgent(user_agent_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/user_agents/parsers.py", line 136, in __init__
    ua_dict = user_agent_parser.Parse(user_agent_string)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ua_parser/user_agent_parser.py", line 258, in Parse
    entry = _lookup(user_agent_string, jsParseBits)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ua_parser/user_agent_parser.py", line 229, in _lookup
    raise TypeError("Expected user agent to be a string, got %r" % ua)
    
   
Image from nov 7th

**Comment by vanschelven** [comment]
I'll pick this one up ASAP; looks fairly trivial, I'll just have to make sure to get the right place to do the validation/sanitation

**Comment by vanschelven** [comment]
I wonder what it says one line below the stacktrace as you pasted it, i.e "TypeError: Expected user agent to be a string, got ..." (the dots)

I'll make this code more robust regardless, I don't ever want funny values to mess with your ability to see the rest of the event.

**Comment by vanschelven** [comment]
Version 0.1.17 should fix this. Curious to hear what the problem turned out to be in the end.

**Comment by olabri** [comment]
Thanks a lot. I ran out of memory on my dockerhost. After I increased it, I have been unable to reproduce this, so it might be a coonnection.

**Comment by olabri** [comment]
found it, suspect its the [ ]`? :-)

```
File "/usr/local/lib/python3.12/site-packages/ua_parser/user_agent_parser.py", line 229, in _lookup                                                                                                                                        raise TypeError("Expected user agent to be a string, got %r" % ua)
TypeError: Expected user agent to be a string, got ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36']
```

**Comment by vanschelven** [comment]
I would suspect the same. What SDK (and version) are you using?

**Comment by vanschelven** [comment]
I think the sending of arrays is actually in error (though we are now robust for it) https://github.com/getsentry/sentry-php/issues/1792

**Comment by vanschelven** [comment]
For now I'm concluding that sending header values in an array is simply a php-sdk-side error that warrants not-crashing but no further special handling.

If ever return to the subject and want to build in generic handling for it, the following may be relevant:

https://www.rfc-editor.org/rfc/rfc2616#section-4.2

> It MUST be possible to combine the multiple header fields into one
> "field-name: field-value" pair, without changing the semantics of the
> message, by appending each subsequent field-value to the first, each
> separated by a comma.
