### ISSUE TITLE
Error when resolving from list view

### ISSUE THREAD

**Issue by olabri** [bugsink/bugsink#14]
New find 

when I try to resolve a issue from the list view I get an error. When resolving from the issue page it goes well. 

![image](https://github.com/user-attachments/assets/5cc9f1ac-0b35-426a-bea4-da85c43822b0)

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/issues/views.py", line 178, in issue_list
    project, unapplied_issue_ids = _issue_list_pt_1(request, project_pk=project_pk, state_filter=state_filter)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

....

 File "/usr/local/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.12/site-packages/MySQLdb/connections.py", line 265, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1292, "Truncated incorrect DOUBLE value: ''")
```

**Comment by vanschelven** [comment]
The stacktrace is missing the vital part. Could you perhaps [dogfood as described here](https://www.bugsink.com/docs/dogfooding/)? 

(instructions are for the latest version, 0.1.19)

**Comment by olabri** [comment]
that is an awseome feature! ill get to it during the weekend

**Comment by olabri** [comment]
dump here : https://gist.github.com/olabri/f79587562c763da1b40288aee8622ff8
