### ISSUE TITLE
Node.js - Internal Server Error

### ISSUE THREAD

**Issue by phil-flip** [bugsink/bugsink#8]
I am aware that currently only Python is supported, but I thought, might as well let you know that its currently broken:
When an error...happens, it will give me this error:
```log
app-1  | Internal Server Error: /api/2/envelope/
app-1  | Traceback (most recent call last):
app-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
app-1  |     response = get_response(request)
app-1  |                ^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
app-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
app-1  |     return self.dispatch(request, *args, **kwargs)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
app-1  |     return bound_method(*args, **kwargs)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
app-1  |     return view_func(*args, **kwargs)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
app-1  |     return handler(request, *args, **kwargs)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.12/site-packages/ingest/views.py", line 58, in post
app-1  |     return self._post(request, project_pk)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.12/site-packages/ingest/views.py", line 471, in _post
app-1  |     envelope_headers = parser.get_envelope_headers()
app-1  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.12/site-packages/ingest/parsers.py", line 149, in get_envelope_headers
app-1  |     assert self.envelope_headers is not None
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  | AssertionError
app-1  | 192.168.128.3 - - [10/Oct/2024:01:24:29 +0200] "POST /api/2/envelope/?sentry_key=f54a019e31f646f4bf9780a061906b27&sentry_version=7&sentry_client=sentry.javascript.node%2F8.33.1 HTTP/1.1" 500 886 "-" "-"
```

**Comment by vanschelven** [comment]
Thanks for this report. Indeed, "not supported yet" but I might very well look into it.

Could you [set `KEEP_ENVELOPES`](https://www.bugsink.com/docs/troubleshooting-ingestion-digestion/) and help me out by providing an example of such an error? (If not, I'll probably do the leg-work myself soonish)

**Comment by phil-flip** [comment]
the crash was basically the example from the Sentry Website

Replace the link but make you take https://github.com/bugsink/bugsink/issues/7 in account.

```js
const Sentry = require('@sentry/node');

const packageFile = require('./package.json');

// Ensure to call this before requiring any other modules!
Sentry.init({
  dsn: 'LINK',
  release: packageFile.version,
});

setTimeout(() => {
  throw new Error('We crashed!!!!!');
}, 10);
```

What should I set KEEP_ENVELOPES to?

**Comment by phil-flip** [comment]
So unless I'm doing something wrong... I only get a 404 back.
If you want to, we can jump on a call on Discord and try to recreate it.

**Comment by phil-flip** [comment]
I did notice however, that nodejs has some additional headers. 
```log
app-1  | 192.168.128.3 - - [13/Oct/2024:18:51:37 +0200] "POST /api/2/envelope/?sentry_key=************&sentry_version=7&sentry_client=sentry.javascript.node%2F8.33.1 HTTP/1.1" 500 886 "-" "-"
```
And Python as them not:
```log
app-1  | 192.168.128.3 - - [13/Oct/2024:18:59:21 +0200] "POST /api/2/envelope/ HTTP/1.1" 200 0 "-" "sentry.python/2.16.0"
```

This seems also on Paar with what is in the testfiles for the SDKs

**Comment by vanschelven** [comment]
I had to just get over my fear-of-everything-js to quickly reproduce this, but using your hints from above I've managed. Will keep you posted on an actual solution

**Comment by phil-flip** [comment]
Thank you, for now I moved to Glitchtip, as I needed something fast, as bugs where kinda getting out of hand and i was looking for something that is able to login through OIDC.
I still which the best of luck.

**Comment by vanschelven** [comment]
Root cause: the Nodejs SDK (perhaps other JS SDKs as well?) sends its envelopes in w/ Chunked Transfer-Encoding, and [this was not supported](https://github.com/bugsink/bugsink/issues/9), in a way that errored out very mysteriously.

(If you're behind a proxy, you might not have noticed, because Transfer-Encoding is rewritable by proxies)

**Comment by vanschelven** [comment]
Closing this because #9 was just fixed.
